baseURL = '/'
languageCode = 'en-us'
title = 'Tools by TART'
theme = 'hugo-theme-techdoc'
sectionPagesmenu = 'main'

metaDataFormat = "yaml"

[params]

    # Source Code repository section
    description = "User Manuals for HyperQube and HyperProb" # displayed below title
    github_repository = "https://github.com/TART-MSU/"
    #version = "0.9.7"

    # Documentation Menu section
	# Menu style settings
	menu_style = "slide-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

	menu_exclusion = [
	    "archives",
	    "archive",
	    "blog",
	    "entry",
	    "post",
	    "posts",
	]

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"

    [[menu.main]]
        name = ""
        url = "/hyperprob"

    [[menu.main]]
        name = ""
        url = "/hyperqube"
